site_name: CS3060701 系統開發實務
site_url: https://ntust-115-cs3060701.github.io/

theme:
  favicon: images/favicon.png
  name: material
  palette:
    primary: teal
  features:
    - navigation.expand
    - navigation.path
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - toc.follow
    - toc.hide
    - toc.integrate

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.admonition
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - tables
  - md_in_html
  - footnotes

extra_css:
  - css/mkdocsoad.css
  - css/table.css
  - css/custom.css

nav:
  - index.md
  - API:
    - api/what-is-api.md
    - api/restful.md
  - 認證與授權:
    - auth/1-authn-and-authz.md
    - auth/2-trust-boundary.md
    - auth/3-identity-principal.md
    - auth/4-acl.md
    - auth/5-rbac.md
    - auth/6-abac.md
    - auth/7-scope-and-claim-aud.md
  - 授權載體:
    - token/README.md
    - token/1-jwt.md
    - token/2-opaque-token.md
    - token/3-access-token.md
    - token/4-refresh-token.md
    - token/5-token-management.md
    - token/5-1-token-lifecycle.md
    - token/5-2-token-revocation.md
